### PR TITLE
Fix scss picking up css max

### PR DESCRIPTION
**Pull request by MatthewKennedy**
SCSS seems to run into issues with max() and the css var, use Max to avoid hitting SCSS and rely on css max

### CODE REVIEW

**Comment by oyejorge** [comment]
Is this conflict/fix documented somewhere or just your observation?

**Comment by MatthewKennedy** [comment]
I was getting
```
Sass::SyntaxError: "var(--ts-pr-min)" is not a number for max
```
unless I specify to impost the .css file.

**Comment by MatthewKennedy** [comment]
it is possible that the sass-rails gem is not as good at processing this as the modern processors.

**Comment by tabuna** [comment]
I have the same error when trying to compile resources

```bash
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: "var(--ts-pr-min)" is not a number for `max'
```

**Comment by wooly** [comment]
@oyejorge this is documented here: https://sass-lang.com/documentation/values/calculations#min-and-max

Related reading:
https://github.com/sass/node-sass/issues/2815
https://github.com/sass/libsass/issues/2701

An alternative solution that I've found which might work in this case is to wrap the `max()` in a `calc()` call.

**Comment by morgoth** [comment]
Having the same on 2.2.0. Downgrading to 2.1.0 workarounds the problem

**Comment by oyejorge** [comment]
Just released 2.2.1 with @MatthewKennedy's fix!

**Comment by KeldorDE** [comment]
It seems like the release build has not finished successfully. There is no 2.2.1 Release on GitHub :)

See the Travis CI log: The npm test command has failed:
https://app.travis-ci.com/github/orchidjs/tom-select/jobs/583995455

**Comment by oyejorge** [comment]
Travis is a separate problem. npm is showing 2.2.1 and github releases have to be done manually (all set now)

**Comment by wooly** [comment]
Unfortunately, this isn't working for us as we're using the `dist/css` version of the stylesheets, which have had the capitalization of Max removed: https://cdn.jsdelivr.net/npm/tom-select@2.2.1/dist/css/tom-select.bootstrap4.css (see the `.ts-control` block).

We'll stick with `2.1.0` for now. @MatthewKennedy are you using the css versions or the scss versions?

**Comment by morgoth** [comment]
The 2.2.1 fix did not work for me. I'm getting the same error @oyejorge 
Similar to @wooly setup, I'm using `dist/css`

**Comment by marckohlbrugge** [comment]
@MatthewKennedy Are you suggesting we import `tom-select/src/scss/tom-select.scss` instead? Because I get the same error there as I get with `dist`

**Pull request merged**
