### PR TITLE
fix #712

### LINKED ISSUE #712: [Bug]: alignment issue when selecting and deselecting items
### Bug description

When selecting an item with ctrl+click, the 1px grey border around it disappears, which makes the entire list of options jump by 2px

image
image

### Expected behavior

selecting an option shouldn't change the position of other options

### Steps to reproduce

1. In a multiselect, select two options
2. click on the first one to make it become blue
3. expected result: the other option doesn't move
4. actual result: the other option moves by 2px because the border around the first one disappeared

### Additional context

- OS: all
- Browser all
- Version latest (2.3.1)
- Device: all

found while trying to integrate TomSelect with [SQLPage](https://sql.ophir.dev/)

### PR DESCRIPTION
**Pull request by lovasoa**
This fixes a small layout jerk when clicking one item in a multiselect .

see #712

### CODE REVIEW

**Comment by lovasoa** [comment]
Hello @orchidjs ? Do you think you'll get a chance to have a look at this pull request ? Do you need help maintaining this project ?

I added it as a dependency to https://github.com/lovasoa/SQLpage , and am ready to help with the maintenance.

**Comment by lovasoa** [comment]
is this project dead?

**Comment by nwalters512** [comment]
@lovasoa I've recently taken over as a maintainer, see https://github.com/orchidjs/tom-select/issues/797. It'd be great to have more folks on board!

Regarding this specific bug/PR, let's continue discussion on #712.

**Comment by lovasoa** [comment]
Hi, 
  I'm very happy to see a new maintainer in this project, since it's an important dependency in [sqlpage](https://sql-page.com) !
I don't really remember the specifics of this issue, so you may be right, and I might have mistaken a tabler issue for a tom-select issue :slightly_smiling_face: 

Anyway I fixed this for us by adding an `!important` css rule in sqlpage.

**Comment by nwalters512** [comment]
Gotcha! In that case, I'm going to go ahead and close this PR and the corresponding issue. If you come up with an isolated reproduction that doesn't involve tabler, feel free to post it 🙏

**Pull request closed without merging**
